`define OP_CFGL     1
`define OP_CFGFC    2
`define OP_CFGCV    11
`define OP_CFGIF    12
`define OP_FCLIF    3
`define OP_FCLW     4
`define OP_FCSOF    5
`define OP_CVLIF    13
`define OP_CVLW     14
`define OP_CVSOF    15
`define OP_CVEXEC   16
`define OP_MPLIF    21
`define OP_MPSOF    22
`define OP_MPEXEC   23
`define OP_EOC      31

`define LAYER_FC    1
`define LAYER_CONV  2
`define LAYER_MP    3
